sudo: required
language: generic 
services: 
  - docker
      
before_install:
  - docker build -t harrisonrober/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true harrisonrober/docker-react npm run test
